"""Step-5 rollout — remaining pages as data objects (README copy formulas)."""
import template as T

TEL, PH = T.PHONE_TEL, T.PHONE_DISPLAY

def call(text):
    return text.replace("{tel}", f'<a href="{TEL}">{PH}</a>')

STEP1 = {"title": "Book in minutes", "desc": "Call or schedule online — we confirm your arrival window fast, with same-day service in most cases."}
STEP2 = {"title": "Diagnose & quote upfront", "desc": "We walk you through what's wrong and your options — flat, upfront pricing you approve first."}

def steps(last_title, last_desc, step1=None, step2=None):
    return {"steps": [step1 or STEP1, step2 or STEP2, {"title": last_title, "desc": last_desc}]}

def detail(slug, crumb_parent, name, h1, hl, intro, chips, book_eyebrow, book_title,
           sym_eyebrow, sym_h2, symptoms, callout, wwd_h2, cards, process_,
           faq_eyebrow, faqs, related, img=None, pills=None, promos=None, safety=False):
    d = {
        "breadcrumb": [crumb_parent, (name, "")],
        "h1": h1, "h1Highlight": hl, "intro": intro, "heroChips": chips,
        "bookingCard": {"eyebrow": book_eyebrow, "title": book_title,
                        "sub": "Upfront pricing before any work begins."},
        "symptoms": {"eyebrow": sym_eyebrow, "h2": sym_h2, "items": symptoms,
                     "callout": call(callout), "safety": safety},
        "whatWeDo": {"h2": wwd_h2, "cards": cards} if cards else None,
        "process": process_, "faqEyebrow": faq_eyebrow, "faq": faqs,
        "rail": {"photo": img, "photoSlot": True, "photoLabel": "PHOTO — TECH ON THE JOB",
                 "promos": promos or ["financing", "xplan"]},
        "related": related,
    }
    if pills:
        d["pillNav"] = pills
    if not cards:
        d.pop("whatWeDo")
    return d

def sub(crumbs, h1, hl, intro, pills, sym_eyebrow, sym_h2, symptoms, callout,
        process_, decision, faq_eyebrow, faqs, book_eyebrow, book_title, book_sub,
        sib_label, sibs, img=None, safety=False, schedule_label="Schedule Service",
        promo="xplanSub", trust2="20+ years local"):
    return {
        "breadcrumb": crumbs, "h1": h1, "h1Highlight": hl, "intro": intro,
        "scheduleLabel": schedule_label,
        "pillNav": pills,
        "symptoms": {"eyebrow": sym_eyebrow, "h2": sym_h2, "items": symptoms,
                     "callout": call(callout), "safety": safety},
        "process": process_, "decision": decision,
        "faqEyebrow": faq_eyebrow, "faq": faqs,
        "bookingCard": {"eyebrow": book_eyebrow, "title": book_title, "sub": book_sub, "trust2": trust2},
        "rail": {"promos": [promo], "photo": img},
        "siblings": {"label": sib_label, "items": sibs},
    }

def pillset(label, items, active):
    return {"label": label, "items": [
        {"label": l, "href": h, "active": l == active} for l, h in items]}

FURN_PILLS = [("Overview", "/furnace-heating"), ("Installation", "/furnace-installation"), ("Repair", "/furnace-repair")]
IAQ_PILLS = [("Overview", "/indoor-air-quality"), ("Solutions", "/indoor-air-quality-solutions"),
             ("Importance", "/importance-iaq"), ("FAQ", "/iaq-faq")]
WH_PILLS = [("Overview", "/plumbing/water-heater/overview"), ("Repair", "/plumbing/water-heater/repair"), ("Installation", "/plumbing/water-heater/installation")]
SEW_PILLS = [("Overview", "/plumbing/sewer-line/overview"), ("Repair", "/plumbing/sewer-line/repair"), ("Cleaning", "/plumbing/sewer-line/cleaning")]
SUMP_PILLS = [("Overview", "/plumbing/sump-pump/overview"), ("Repair", "/plumbing/sump-pump/repair"), ("Installation", "/plumbing/sump-pump/installation")]
GAS_PILLS = [("Overview", "/plumbing/gas-line/overview"), ("Repair", "/plumbing/gas-line/repair"), ("Installation", "/plumbing/gas-line/installation")]

HVAC_CRUMB = ("Heating & Air", "/services")
PLUMB_CRUMB = ("Plumbing", "/plumbing/services")

SPEED_FAQ = {"q": "How fast can you get here?",
    "a": "In most cases, same day — about 90% of our calls are handled the day you reach out, with 24/7 emergency service when it can't wait."}
BRANDS_FAQ = {"q": "Do you service all brands?",
    "a": "Yes — every major make and model, regardless of who installed it."}

# ======================================================================
# HVAC details
# ======================================================================
HVAC_PAGES = {}

HVAC_PAGES["furnace-heating.html"] = detail(
    "furnace-heating", HVAC_CRUMB, "Furnace & Heating",
    "Reliable heat, {X}.", "all winter long",
    "Furnace repairs, installations, and safety checks from the locally owned Extreme Team — upfront pricing and warm air back fast.",
    ["4.9 on Google", "90% Same-Day Service", "24/7 Emergency"],
    "BOOK HEATING SERVICE", "Get a tech to your door.",
    "FURNACE TROUBLE?", "Signs it's time to call.",
    ["Blowing cold or lukewarm air", "Short cycling on and off", "Yellow or flickering burner flame",
     "Burning or musty smells", "Banging or scraping sounds", "Heating bills creeping up"],
    "<b>Safety first:</b> smell gas or suspect carbon monoxide? Leave the house first, then call {tel} — 24/7.",
    "Repair, replace, or maintain — we handle it all.",
    [{"title": "Furnace Repair", "desc": "Fast diagnosis and honest repair options for every make and model — 24/7 for no-heat calls.", "href": "/furnace-repair"},
     {"title": "Furnace Installation", "desc": "Right-sized, high-efficiency furnaces installed clean — with flexible financing options.", "href": "/furnace-installation"},
     {"title": "Heating Tune-Ups", "desc": "Seasonal safety checks that catch small issues early — included twice a year with X-Plan.", "href": "/maintenance"}],
    steps("Fixed right, safety-checked", "Every visit ends with a full safety check — heat exchanger, venting, and CO included."),
    "HEATING QUESTIONS",
    [SPEED_FAQ,
     {"q": "Should I repair or replace my furnace?",
      "a": "Under 12 years old with a minor issue, repair usually wins. Past 15 years with a major failure, replacement often costs less over time. We'll give you both numbers — no pressure."},
     BRANDS_FAQ,
     {"q": "How often should my furnace be serviced?",
      "a": "Once a year, ideally in fall before the heating season — it keeps efficiency up and catches safety issues early."}],
    [{"title": "Air Conditioning", "href": "/air-conditioning"},
     {"title": "Heat Pump Services", "href": "/heat-pump"},
     {"title": "Thermostat Services", "href": "/thermostat"}],
    pills=pillset("FURNACE & HEATING", FURN_PILLS, "Overview"), safety=True)

HVAC_PAGES["heat-pump.html"] = detail(
    "heat-pump", HVAC_CRUMB, "Heat Pump Services",
    "Year-round comfort from {X}.", "one system",
    "Heat pump repair, installation, and tune-ups for Dayton & Cincinnati homes — efficient heating and cooling with upfront pricing.",
    ["4.9 on Google", "90% Same-Day Service", "24/7 Emergency"],
    "BOOK HEAT PUMP SERVICE", "Get a tech to your door.",
    "HEAT PUMP ACTING UP?", "Signs it's time to call.",
    ["Not heating or cooling like it used to", "Ice building up on the outdoor unit", "Running constantly or short cycling",
     "Grinding, rattling, or squealing", "Blowing the wrong temperature air", "Energy bills creeping up"],
    "Noticing more than one? Small heat pump problems become compressor problems — call {tel} before it gets expensive.",
    "Repair, replace, or maintain — we handle it all.",
    [{"title": "Heat Pump Repair", "desc": "Fast diagnostics for every make and model — approved by you before we start.", "href": "/contact"},
     {"title": "Heat Pump Installation", "desc": "Right-sized, high-efficiency systems installed clean — with flexible financing options.", "href": "/financing-options"},
     {"title": "Heat Pump Tune-Ups", "desc": "Twice-a-year checkups keep efficiency high — included with X-Plan.", "href": "/maintenance"}],
    steps("Fixed right, guaranteed", "Clean workmanship, tested before we leave, and backed by our satisfaction guarantee."),
    "HEAT PUMP QUESTIONS",
    [SPEED_FAQ,
     {"q": "Do heat pumps work in Ohio winters?",
      "a": "Yes — modern cold-climate heat pumps heat efficiently well below freezing, and dual-fuel setups pair a heat pump with a furnace for the coldest snaps."},
     {"q": "Should I repair or replace my heat pump?",
      "a": "Under 10 years old with a minor issue, repair usually wins. Past 12–15 years with a compressor-level failure, replacement often costs less over time."},
     BRANDS_FAQ],
    [{"title": "Air Conditioning", "href": "/air-conditioning"},
     {"title": "Furnace & Heating", "href": "/furnace-heating"},
     {"title": "Indoor Air Quality", "href": "/indoor-air-quality"}])

HVAC_PAGES["duct-cleaning.html"] = detail(
    "duct-cleaning", HVAC_CRUMB, "Duct Cleaning",
    "Cleaner air starts {X}.", "in your ducts",
    "Professional duct cleaning and air balancing for Dayton & Cincinnati homes — better airflow, less dust, upfront pricing.",
    ["4.9 on Google", "Locally Owned", "Upfront Pricing"],
    "BOOK DUCT CLEANING", "Get a tech to your door.",
    "DUSTY HOUSE?", "Signs your ducts need attention.",
    ["Dust returns right after cleaning", "Musty smells when the system runs", "Uneven airflow between rooms",
     "Allergies acting up indoors", "Visible dust at the vents", "Ducts never professionally cleaned"],
    "Remodeling dust, pets, or allergies? Call {tel} and we'll tell you honestly whether cleaning will help.",
    "Cleaning, balancing, and sealing — done right.",
    [{"title": "Duct Cleaning", "desc": "Truck-powered cleaning that pulls dust and debris from the whole duct system.", "href": "/contact"},
     {"title": "Air Balancing", "desc": "Even out hot and cold rooms with airflow measurement and adjustment.", "href": "/contact"},
     {"title": "Dryer Vent Cleaning", "desc": "Faster dry times and less fire risk — often same visit.", "href": "/contact"}],
    steps("Cleaner air, guaranteed", "Before-and-after photos of your ducts, and everything left spotless."),
    "DUCT QUESTIONS",
    [SPEED_FAQ,
     {"q": "How often should ducts be cleaned?",
      "a": "Every 3–5 years for most homes — sooner after a remodel, with shedding pets, or if allergies flare indoors."},
     {"q": "Will duct cleaning help my allergies?",
      "a": "It can — removing built-up dust, dander, and debris reduces what recirculates. Pair it with filtration for the biggest improvement."}],
    [{"title": "Indoor Air Quality", "href": "/indoor-air-quality"},
     {"title": "Air Conditioning", "href": "/air-conditioning"},
     {"title": "Humidifier Services", "href": "/humidifier"}])

HVAC_PAGES["thermostat.html"] = detail(
    "thermostat", HVAC_CRUMB, "Thermostat Services",
    "Smarter comfort, {X}.", "one tap away",
    "Smart thermostat installation, setup, and troubleshooting — get more comfort and lower bills from the system you already own.",
    ["4.9 on Google", "Locally Owned", "Upfront Pricing"],
    "BOOK THERMOSTAT SERVICE", "Get a tech to your door.",
    "THERMOSTAT TROUBLE?", "Signs it's time to call.",
    ["Blank or unresponsive display", "Temperature doesn't match the setting", "System won't turn on or off",
     "Short cycling on and off", "Wi-Fi or app won't connect", "Rooms never feel right"],
    "Thermostat acting up? It's often the cheapest fix in HVAC — call {tel} before assuming the worst.",
    "Install, program, and troubleshoot — any brand.",
    [{"title": "Smart Thermostat Install", "desc": "Nest, Ecobee, Honeywell and more — wired, mounted, and connected right.", "href": "/contact"},
     {"title": "Setup & Programming", "desc": "Schedules, sensors, and app setup tuned to how your home actually runs.", "href": "/contact"},
     {"title": "Thermostat Repair", "desc": "Wiring faults, compatibility issues, and replacements — diagnosed fast.", "href": "/contact"}],
    steps("Working right, explained", "We test heating and cooling cycles and walk you through the controls before we leave."),
    "THERMOSTAT QUESTIONS",
    [SPEED_FAQ,
     {"q": "Which smart thermostat should I buy?",
      "a": "It depends on your system's wiring and staging. We'll recommend one that actually works with your equipment — and install it right the first time."},
     {"q": "Can a new thermostat lower my bills?",
      "a": "Yes — smart schedules and occupancy sensing typically trim 8–12% off heating and cooling costs."}],
    [{"title": "Air Conditioning", "href": "/air-conditioning"},
     {"title": "Furnace & Heating", "href": "/furnace-heating"},
     {"title": "HVAC Inspections", "href": "/inspection"}])

HVAC_PAGES["humidifier.html"] = detail(
    "humidifier", HVAC_CRUMB, "Humidifier Services",
    "Whole-home humidity, {X}.", "done right",
    "Whole-home humidifier installation and service — end dry winter air, static shocks, and cracked wood floors.",
    ["4.9 on Google", "Locally Owned", "Upfront Pricing"],
    "BOOK HUMIDIFIER SERVICE", "Get a tech to your door.",
    "DRY AIR PROBLEMS?", "Signs your home needs humidity help.",
    ["Static shocks all winter", "Dry skin, lips, and sinuses", "Cracking wood floors or furniture",
     "Gaps opening in trim and doors", "Waking up congested", "Humidity readings below 30%"],
    "Dry air is hardest on homes in an Ohio winter — call {tel} and we'll size the right solution.",
    "Install, service, and balance — whole-home.",
    [{"title": "Humidifier Installation", "desc": "Bypass, fan-powered, or steam — matched to your home and furnace.", "href": "/contact"},
     {"title": "Humidifier Service", "desc": "Pad replacement, cleaning, and tune-ups to keep output steady.", "href": "/contact"},
     {"title": "Dehumidification", "desc": "Summer moisture control for basements and whole homes.", "href": "/indoor-air-quality"}],
    steps("Comfort, dialed in", "We set target humidity by season and show you how to adjust it."),
    "HUMIDIFIER QUESTIONS",
    [SPEED_FAQ,
     {"q": "What humidity should my home be?",
      "a": "30–50% depending on season — low enough to avoid window condensation in winter, high enough to stay comfortable."},
     {"q": "Do whole-home humidifiers need maintenance?",
      "a": "Yes — an annual pad change and cleaning keeps them working and sanitary. We handle it during X-Plan tune-ups."}],
    [{"title": "Indoor Air Quality", "href": "/indoor-air-quality"},
     {"title": "Duct Cleaning", "href": "/duct-cleaning"},
     {"title": "Furnace & Heating", "href": "/furnace-heating"}])

HVAC_PAGES["inspection.html"] = detail(
    "inspection", HVAC_CRUMB, "HVAC Inspections",
    "Know your system, {X}.", "before it surprises you",
    "Full-system HVAC inspections for peace of mind — home purchases, seasonal checkups, and honest second opinions.",
    ["4.9 on Google", "Locally Owned", "Upfront Pricing"],
    "BOOK AN INSPECTION", "Get a tech to your door.",
    "WHY INSPECT?", "When an inspection pays for itself.",
    ["Buying or selling a home", "System is 10+ years old", "Bills higher than last year",
     "Comfort varies room to room", "No service records on file", "Second opinion on a big quote"],
    "Want eyes on it before you commit? Call {tel} — we'll tell you what's real and what can wait.",
    "Checked bumper to bumper.",
    [{"title": "Full-System Inspection", "desc": "Heating, cooling, ductwork, and safety — documented with photos.", "href": "/contact"},
     {"title": "Pre-Purchase Checks", "desc": "Know what you're buying before you close — with repair estimates.", "href": "/contact"},
     {"title": "Second Opinions", "desc": "A big repair quote deserves a second set of eyes — no pressure, just numbers.", "href": "/contact"}],
    steps("A report you can act on", "Findings in plain English, prioritized by safety, urgency, and cost."),
    "INSPECTION QUESTIONS",
    [SPEED_FAQ,
     {"q": "What does an HVAC inspection include?",
      "a": "Combustion safety, refrigerant performance, electrical checks, airflow, and ductwork condition — documented with photos and plain-English findings."},
     {"q": "Is an inspection the same as a tune-up?",
      "a": "No — an inspection documents condition; a tune-up services the equipment. X-Plan includes both, twice a year."}],
    [{"title": "Maintenance Plans", "href": "/maintenance"},
     {"title": "Air Conditioning", "href": "/air-conditioning"},
     {"title": "Furnace & Heating", "href": "/furnace-heating"}])

HVAC_PAGES["indoor-air-quality.html"] = detail(
    "indoor-air-quality", HVAC_CRUMB, "Indoor Air Quality",
    "Breathe easier {X}.", "at home",
    "Filtration, purification, and humidity control for Dayton & Cincinnati homes — cleaner air from the team you already trust.",
    ["4.9 on Google", "Locally Owned", "Upfront Pricing"],
    "BOOK AIR QUALITY HELP", "Get a tech to your door.",
    "AIR FEELING OFF?", "Signs your air quality needs attention.",
    ["Allergies flare up indoors", "Dust builds up fast", "Lingering odors or stale air",
     "Too humid in summer, too dry in winter", "Mold or musty smells", "Everyone sleeps better away from home"],
    "Air quality problems compound quietly — call {tel} and we'll find the source, not just the symptom.",
    "Filter it, purify it, balance it.",
    [{"title": "Air Quality Solutions", "desc": "Filtration, UV purification, and ventilation matched to your home.", "href": "/indoor-air-quality-solutions"},
     {"title": "Why IAQ Matters", "desc": "What indoor air actually carries — and what it does to sleep and health.", "href": "/importance-iaq"},
     {"title": "IAQ Questions", "desc": "Straight answers on filters, purifiers, humidity, and more.", "href": "/iaq-faq"}],
    steps("Cleaner air, measured", "We verify results with before-and-after readings — not promises."),
    "AIR QUALITY QUESTIONS",
    [SPEED_FAQ,
     {"q": "What actually improves indoor air?",
      "a": "Source control first, then filtration, then purification — in that order. We'll tell you what your home actually needs, not a package."},
     {"q": "Do UV purifiers work?",
      "a": "Against biological growth on coils and airborne microbes, yes — when sized and placed correctly. They're not a fix for dust."}],
    [{"title": "Duct Cleaning", "href": "/duct-cleaning"},
     {"title": "Humidifier Services", "href": "/humidifier"},
     {"title": "Air Conditioning", "href": "/air-conditioning"}],
    pills=pillset("INDOOR AIR QUALITY", IAQ_PILLS, "Overview"))

# X-Plan page — restyled to tokens, membership content kept
HVAC_PAGES["maintenance.html"] = detail(
    "maintenance", HVAC_CRUMB, "X-Plan Maintenance",
    "Never think about {X} again.", "tune-ups",
    "The X-Plan: two seasonal tune-ups a year, priority scheduling, 15% off repairs, and a 5-year repair warranty — $249/year or $20.75/month.",
    ["4.9 on Google", "Priority Scheduling", "15% Off Repairs"],
    "JOIN X-PLAN", "Membership starts today.",
    "EVERY VISIT INCLUDES", "What your tune-up covers.",
    ["Full system inspection & safety check", "Capacitor, relay & thermostat testing", "Compressor amp draws",
     "Drain line cleaning", "Pressure check", "Light coil cleaning"],
    "Questions about membership or billing? Call {tel} — we'll walk you through it.",
    "Membership that pays for itself.",
    [{"title": "Priority Scheduling", "desc": "Members go to the front of the line — especially during heat waves and cold snaps.", "href": "/contact"},
     {"title": "15% Off Repairs", "desc": "Every repair, every visit — plus a reduced service fee.", "href": "/contact"},
     {"title": "5-Year Repair Warranty", "desc": "Our work, guaranteed five times longer than the industry standard.", "href": "/contact"}],
    steps("Covered, year-round", "We schedule your spring and fall visits automatically — you don't lift a finger."),
    "X-PLAN QUESTIONS",
    [{"q": "How fast can members get service?",
      "a": "Members get priority scheduling — during busy seasons that's often the difference between same-day and next-week."},
     {"q": "What does X-Plan cost?",
      "a": "$249 a year, or $20.75 a month — including both seasonal tune-ups, 15% off repairs, a reduced service fee, and the 5-year repair warranty."},
     {"q": "Does X-Plan cover both heating and cooling?",
      "a": "Yes — one tune-up each for the heating and cooling seasons, covering your full system."}],
    [{"title": "HVAC Inspections", "href": "/inspection"},
     {"title": "Air Conditioning", "href": "/air-conditioning"},
     {"title": "Furnace & Heating", "href": "/furnace-heating"}])

# ---- HVAC sub-pages (2d pattern) ----
HVAC_SUBS = {}

HVAC_SUBS["furnace-installation.html"] = sub(
    [HVAC_CRUMB, ("Furnace & Heating", "/furnace-heating"), ("Installation", "")],
    "A new furnace, {X}.", "installed right",
    "Right-sized, high-efficiency furnaces installed clean and to code — with honest sizing math and flexible financing.",
    pillset("FURNACE & HEATING", FURN_PILLS, "Installation"),
    "TIME TO REPLACE?", "Signs a new furnace makes sense.",
    ["Furnace is 15+ years old", "Repairs are getting frequent", "Bills climbing year over year",
     "Some rooms never get warm", "Yellow burner flame or soot", "Major component failure"],
    "Not sure repair vs. replace? Call {tel} — we'll give you both numbers, no pressure.",
    steps("Installed clean, tested hot", "Code-compliant gas, venting, and electrical — commissioned and walked through before we leave.",
          step2={"title": "Sized & quoted upfront", "desc": "A real load calculation — not a guess — with flat pricing and financing options."}),
    {"title": "Repair or replace?",
     "desc": "If your furnace is under 12 years old and the fix is minor, repair usually wins. We'll lay out both paths honestly.",
     "linkLabel": "Furnace Repair →", "href": "/furnace-repair"},
    "INSTALLATION QUESTIONS",
    [{"q": "How fast can you install a new furnace?",
      "a": "Usually within a day or two of your estimate — and same-week in most cases, even in season."},
     {"q": "What size furnace do I need?",
      "a": "It depends on your home's real heat loss — we run a load calculation instead of matching the old label."},
     {"q": "Is financing available?",
      "a": "Yes — flexible monthly options on qualifying systems. We'll show you payment scenarios with your quote."}],
    "BOOK AN ESTIMATE", "Free replacement estimates.", "Honest numbers, no pressure.",
    "FURNACE & HEATING",
    [{"title": "Furnace & Heating Overview", "href": "/furnace-heating"},
     {"title": "Furnace Repair", "href": "/furnace-repair"},
     {"title": "Thermostat Services", "href": "/thermostat"}],
    schedule_label="Schedule Estimate")

HVAC_SUBS["indoor-air-quality-solutions.html"] = sub(
    [HVAC_CRUMB, ("Indoor Air Quality", "/indoor-air-quality"), ("Solutions", "")],
    "Air quality solutions {X}.", "that actually work",
    "Filtration, UV purification, ventilation, and humidity control — matched to your home's actual problems, not a package.",
    pillset("INDOOR AIR QUALITY", IAQ_PILLS, "Solutions"),
    "WHAT WE SOLVE", "Match the fix to the problem.",
    ["Dust & dander — media filtration", "Odors & VOCs — carbon + ventilation", "Microbes & mold — UV purification",
     "Dry winter air — whole-home humidifier", "Humid summers — dehumidification", "Stale air — fresh-air ventilation"],
    "Not sure which applies to your home? Call {tel} — we diagnose before we recommend.",
    steps("Installed & measured", "Solutions installed clean, then verified with before-and-after readings.",
          step2={"title": "Assess & recommend", "desc": "We test your air and match solutions to the actual problem — no bundles you don't need."}),
    {"title": "Start with an air quality check",
     "desc": "A short assessment tells us whether filtration, purification, or humidity control will move the needle for your home.",
     "linkLabel": "IAQ Overview →", "href": "/indoor-air-quality"},
    "SOLUTIONS QUESTIONS",
    [{"q": "How fast can solutions be installed?",
      "a": "Most filtration and UV installs happen in a single visit — often the same week you call."},
     {"q": "Which filter rating should I use?",
      "a": "The highest MERV your system can handle without choking airflow — we'll check yours before recommending."},
     {"q": "Do I need a whole-home system?",
      "a": "Not always. Sometimes a filter upgrade and duct sealing beat an expensive purifier. We'll tell you honestly."}],
    "BOOK AIR QUALITY HELP", "Cleaner air starts here.", "Assessment and upfront pricing first.",
    "INDOOR AIR QUALITY",
    [{"title": "IAQ Overview", "href": "/indoor-air-quality"},
     {"title": "Why IAQ Matters", "href": "/importance-iaq"},
     {"title": "IAQ FAQ", "href": "/iaq-faq"}])

HVAC_SUBS["importance-iaq.html"] = sub(
    [HVAC_CRUMB, ("Indoor Air Quality", "/indoor-air-quality"), ("Importance", "")],
    "Why indoor air {X}.", "matters",
    "Indoor air is often 2–5× more polluted than outdoor air — here's what that means for your sleep, health, and home.",
    pillset("INDOOR AIR QUALITY", IAQ_PILLS, "Importance"),
    "WHAT'S IN YOUR AIR?", "What indoor air carries.",
    ["Dust, dander & pollen", "VOCs from cleaners & furnishings", "Excess humidity feeding mold",
     "Dry air irritating sinuses", "Cooking & combustion byproducts", "Microbes recirculating through ducts"],
    "Concerned about what your family breathes? Call {tel} for an honest air quality assessment.",
    steps("Fixed at the source", "We treat causes — filtration, ventilation, humidity — not just symptoms.",
          step2={"title": "Test & explain", "desc": "We measure what's actually in your air and walk you through the results."}),
    {"title": "See the solutions",
     "desc": "From filtration to humidity control — match the right fix to what your air actually carries.",
     "linkLabel": "Air Quality Solutions →", "href": "/indoor-air-quality-solutions"},
    "IAQ QUESTIONS",
    [{"q": "How quickly can you assess our air?",
      "a": "Usually within a few days — the assessment itself takes under an hour in most homes."},
     {"q": "Does indoor air really affect sleep?",
      "a": "Yes — particulates, CO2 buildup, and humidity extremes all measurably disrupt sleep quality."},
     {"q": "Is my home too new to have air problems?",
      "a": "Newer, tighter homes often trap more pollutants, not fewer — ventilation matters more, not less."}],
    "BOOK AN ASSESSMENT", "Know what you're breathing.", "Measured, explained, and priced upfront.",
    "INDOOR AIR QUALITY",
    [{"title": "IAQ Overview", "href": "/indoor-air-quality"},
     {"title": "Air Quality Solutions", "href": "/indoor-air-quality-solutions"},
     {"title": "IAQ FAQ", "href": "/iaq-faq"}])

HVAC_SUBS["iaq-faq.html"] = sub(
    [HVAC_CRUMB, ("Indoor Air Quality", "/indoor-air-quality"), ("FAQ", "")],
    "Air quality questions, {X}.", "answered straight",
    "The questions homeowners actually ask about filters, purifiers, humidity, and duct cleaning — answered without the sales pitch.",
    pillset("INDOOR AIR QUALITY", IAQ_PILLS, "FAQ"),
    "QUICK ANSWERS", "The short version.",
    ["Filters: highest MERV your system allows", "UV: great for coils, not for dust", "Humidity: keep it 30–50%",
     "Duct cleaning: every 3–5 years", "Ventilation: tight homes need it most", "Odors: find the source first"],
    "Have a question that isn't here? Call {tel} — real answers from real techs.",
    steps("Solved, not sold", "If the honest answer is a $40 filter, that's what we'll tell you.",
          step2={"title": "Ask us anything", "desc": "Describe what you're noticing — we'll narrow the cause fast."}),
    {"title": "Dig into the details",
     "desc": "The full breakdown of what's in indoor air and which solutions match which problems.",
     "linkLabel": "Why IAQ Matters →", "href": "/importance-iaq"},
    "AIR QUALITY FAQ",
    [{"q": "How fast can you help with an air quality problem?",
      "a": "Assessments usually within days; most solutions install in a single visit."},
     {"q": "What's the single best upgrade for air quality?",
      "a": "For most homes: a properly-sized media filter, checked seasonally. It outperforms most gadgets."},
     {"q": "Does duct cleaning improve air quality?",
      "a": "It helps when ducts are genuinely dirty — after remodels, with pets, or if never cleaned. We'll look first and tell you honestly."}],
    "STILL HAVE QUESTIONS?", "Ask a real tech.", "No pressure, no pitch — just answers.",
    "INDOOR AIR QUALITY",
    [{"title": "IAQ Overview", "href": "/indoor-air-quality"},
     {"title": "Air Quality Solutions", "href": "/indoor-air-quality-solutions"},
     {"title": "Why IAQ Matters", "href": "/importance-iaq"}])

# ======================================================================
# Plumbing details (no pill nav)
# ======================================================================
PLUMB_PAGES = {}

PLUMB_PAGES["clogged-drain.html"] = detail(
    "clogged-drain", PLUMB_CRUMB, "Clogged Drain",
    "Clogged drains, {X}.", "cleared fast",
    "From slow sinks to backed-up main lines — cleared fast by licensed plumbers with upfront pricing.",
    ["4.9 on Google", "Same-Day Service", "Licensed Plumbers"],
    "BOOK DRAIN SERVICE", "Get a plumber to your door.",
    "DRAIN TROUBLE?", "Signs it's more than a slow sink.",
    ["Water backing up in tubs or sinks", "Gurgling from drains or toilet", "Sewage smells indoors",
     "Multiple slow drains at once", "Water around floor drains", "Clogs that keep coming back"],
    "Multiple drains backing up at once? That's a main-line warning — call {tel} before it becomes a mess.",
    "Cleared, cleaned, and diagnosed.",
    [{"title": "Drain Clearing", "desc": "Augers and hydro-jetting to clear the clog — not just poke a hole in it.", "href": "/contact"},
     {"title": "Camera Inspection", "desc": "See what's really down there — roots, grease, or a bigger sewer issue.", "href": "/plumbing/sewer-line/overview"},
     {"title": "Preventive Cleaning", "desc": "Scheduled cleanings for clog-prone lines before they back up.", "href": "/contact"}],
    steps("Cleared and verified", "We run water, confirm full flow, and tell you what caused it — so it doesn't repeat."),
    "DRAIN QUESTIONS",
    [SPEED_FAQ,
     {"q": "Why does my drain keep clogging?",
      "a": "Repeat clogs usually mean buildup or damage deeper in the line — a camera inspection finds the real cause."},
     {"q": "Are chemical drain cleaners safe?",
      "a": "We don't recommend them — they damage pipes and rarely clear the real blockage. Mechanical clearing is safer and lasts."}],
    [{"title": "Sewer Line Services", "href": "/plumbing/sewer-line/overview"},
     {"title": "Leak Detection", "href": "/plumbing/leak-detection"},
     {"title": "Toilet Repair", "href": "/plumbing/toilet-repair"}],
    promos=["scheduleFast", "specials"])

PLUMB_PAGES["emergency-plumbing.html"] = detail(
    "emergency-plumbing", PLUMB_CRUMB, "Emergency Plumbing",
    "Plumbing emergencies, {X}.", "handled 24/7",
    "Burst pipes, backups, and no-water emergencies — real 24/7 response from licensed local plumbers.",
    ["4.9 on Google", "24/7 Response", "Licensed Plumbers"],
    "EMERGENCY? BOOK NOW", "We're on our way.",
    "IS IT AN EMERGENCY?", "Call now if you see these.",
    ["Water you can't shut off", "Sewage backing up indoors", "Burst or frozen pipe",
     "No water to the house", "Water heater leaking fast", "Gas smell near appliances"],
    "<b>Safety first:</b> for gas smells, leave the house before calling {tel}. For water, shut the main valve if you can reach it safely.",
    "Stabilize, fix, and prevent.",
    [{"title": "Emergency Response", "desc": "Nights, weekends, and holidays — a real plumber, not a call center promise.", "href": "/contact"},
     {"title": "Burst Pipe Repair", "desc": "Fast isolation and repair to stop damage from spreading.", "href": "/plumbing/leak-detection"},
     {"title": "Backup Clearing", "desc": "Sewage backups cleared and sanitized — and the cause identified.", "href": "/plumbing/clogged-drain"}],
    steps("Fixed and protected", "We fix the emergency, then show you how to prevent the next one.",
          step1={"title": "Call any hour", "desc": "24/7 dispatch — we triage on the phone and get a plumber moving."}),
    "EMERGENCY QUESTIONS",
    [{"q": "How fast can you get here in an emergency?",
      "a": "Emergency calls get priority dispatch around the clock — we'll give you a real arrival window when you call, not a whole-day guess."},
     {"q": "What should I do while I wait?",
      "a": "Shut the nearest valve (or the main), move valuables clear, and don't run water to affected drains. We'll talk you through it on the phone."},
     {"q": "Do emergencies cost more?",
      "a": "After-hours dispatch differs from standard visits, but pricing is still flat and upfront — approved by you before work starts."}],
    [{"title": "Leak Detection", "href": "/plumbing/leak-detection"},
     {"title": "Clogged Drain", "href": "/plumbing/clogged-drain"},
     {"title": "Water Heater Services", "href": "/plumbing/water-heater/overview"}],
    promos=["scheduleFast", "specials"], safety=True)

PLUMB_PAGES["leak-detection.html"] = detail(
    "leak-detection", PLUMB_CRUMB, "Leak Detection",
    "Hidden leaks, {X}.", "found fast",
    "Electronic leak detection that finds the problem without tearing up your home — then fixes it with upfront pricing.",
    ["4.9 on Google", "Non-Invasive", "Licensed Plumbers"],
    "BOOK LEAK DETECTION", "Get a plumber to your door.",
    "SUSPECT A LEAK?", "Signs water is going somewhere it shouldn't.",
    ["Water bill jumped without reason", "Meter runs with everything off", "Damp spots on walls or ceilings",
     "Musty smells or mold patches", "Warm spots on the floor", "Sound of running water at night"],
    "Leaks only get bigger — call {tel} before a drip becomes drywall.",
    "Find it, fix it, verify it.",
    [{"title": "Electronic Detection", "desc": "Acoustic and thermal tools pinpoint leaks behind walls and under slabs.", "href": "/contact"},
     {"title": "Leak Repair", "desc": "Targeted repairs with minimal opening — priced before we cut.", "href": "/contact"},
     {"title": "Repipe Options", "desc": "For aging systems that keep leaking, honest whole-home repipe numbers.", "href": "/contact"}],
    steps("Fixed and verified", "We pressure-test after repair and confirm the meter sits still."),
    "LEAK QUESTIONS",
    [SPEED_FAQ,
     {"q": "Can you find a leak without opening walls?",
      "a": "Usually, yes — acoustic and thermal detection narrows it to inches before we open anything."},
     {"q": "How do I check if I have a leak?",
      "a": "Turn everything off and watch your water meter for 15 minutes. If it moves, call us."}],
    [{"title": "Emergency Plumbing", "href": "/plumbing/emergency-plumbing"},
     {"title": "Sewer Line Services", "href": "/plumbing/sewer-line/overview"},
     {"title": "Water Treatment", "href": "/plumbing/water-treatment"}],
    promos=["scheduleFast", "specials"])

PLUMB_PAGES["toilet-repair.html"] = detail(
    "toilet-repair", PLUMB_CRUMB, "Toilet Repair",
    "Toilet trouble, {X}.", "fixed right",
    "Running, clogged, leaking, or rocking — toilets repaired or replaced by licensed plumbers with upfront pricing.",
    ["4.9 on Google", "Same-Day Service", "Licensed Plumbers"],
    "BOOK TOILET REPAIR", "Get a plumber to your door.",
    "TOILET ACTING UP?", "Signs it needs a pro.",
    ["Runs constantly or randomly", "Clogs keep coming back", "Water around the base",
     "Rocks or shifts when used", "Weak or incomplete flush", "Tank refills on its own"],
    "A running toilet can waste 200 gallons a day — call {tel} and stop paying for it.",
    "Repair, replace, or upgrade.",
    [{"title": "Toilet Repair", "desc": "Fill valves, flappers, seals, and clogs — fixed in one visit, priced first.", "href": "/contact"},
     {"title": "Toilet Replacement", "desc": "Efficient new models installed clean — old unit hauled away.", "href": "/contact"},
     {"title": "Leak Sealing", "desc": "Base and tank leaks stopped before they rot the floor.", "href": "/plumbing/leak-detection"}],
    steps("Fixed and flush-tested", "We test repeatedly, check for leaks, and leave the bathroom spotless."),
    "TOILET QUESTIONS",
    [SPEED_FAQ,
     {"q": "Repair or replace my toilet?",
      "a": "Repairs win for valves and seals; replacement wins for cracked bowls, constant clogs, or pre-1994 water hogs. We'll price both."},
     {"q": "Why does my toilet keep running?",
      "a": "Usually a worn flapper or fill valve — a fast, inexpensive fix that pays for itself in water savings."}],
    [{"title": "Clogged Drain", "href": "/plumbing/clogged-drain"},
     {"title": "Leak Detection", "href": "/plumbing/leak-detection"},
     {"title": "Water Heater Services", "href": "/plumbing/water-heater/overview"}],
    promos=["scheduleFast", "specials"])

PLUMB_PAGES["water-treatment.html"] = detail(
    "water-treatment", PLUMB_CRUMB, "Water Treatment",
    "Better water, {X}.", "from every tap",
    "Softeners, filtration, and reverse osmosis for Dayton & Cincinnati homes — matched to your water, not a sales quota.",
    ["4.9 on Google", "Free Water Testing", "Licensed Plumbers"],
    "BOOK WATER TESTING", "Get a plumber to your door.",
    "HARD WATER SIGNS?", "What your water is telling you.",
    ["White scale on fixtures", "Spots on dishes and glass", "Dry skin and dull laundry",
     "Metallic taste or odor", "Appliances failing early", "Cloudy or off-color water"],
    "Curious what's in your water? Call {tel} — we test first and recommend second.",
    "Soften, filter, or purify.",
    [{"title": "Water Softeners", "desc": "End scale buildup and protect your appliances — sized to your usage.", "href": "/contact"},
     {"title": "Whole-Home Filtration", "desc": "Cleaner water at every tap — chlorine, sediment, and odor removed.", "href": "/contact"},
     {"title": "Reverse Osmosis", "desc": "Bottle-quality drinking water from your kitchen tap.", "href": "/contact"}],
    steps("Installed and tested", "We verify results at the tap and set up simple maintenance.",
          step2={"title": "Test & recommend", "desc": "A real water test drives the recommendation — city or well."}),
    "WATER QUESTIONS",
    [SPEED_FAQ,
     {"q": "City water or well — does it matter?",
      "a": "Yes — city water usually needs chlorine and hardness treatment; wells vary widely and need testing first."},
     {"q": "Will a softener make water taste salty?",
      "a": "No — properly set softeners add far less sodium than people expect, and an RO tap removes it entirely for drinking."}],
    [{"title": "Water Heater Services", "href": "/plumbing/water-heater/overview"},
     {"title": "Leak Detection", "href": "/plumbing/leak-detection"},
     {"title": "Clogged Drain", "href": "/plumbing/clogged-drain"}],
    promos=["scheduleFast", "specials"])

# ---- Plumbing multi-child families ----
def family_overview(folder, name, h1, hl, intro, pills, sym_eyebrow, sym_h2, symptoms,
                    callout, wwd_h2, cards, last_step, faqs, related, safety=False, img=None):
    return detail(folder, PLUMB_CRUMB, name, h1, hl, intro,
        ["4.9 on Google", "Same-Day Service", "Licensed Plumbers"],
        f"BOOK {name.upper()}", "Get a plumber to your door.",
        sym_eyebrow, sym_h2, symptoms, callout, wwd_h2, cards,
        steps(last_step[0], last_step[1]),
        f"{name.split()[0].upper()} QUESTIONS", faqs, related,
        pills=pills, promos=["scheduleFast", "specials"], safety=safety, img=img)

PLUMB_FAMILIES = {}

PLUMB_FAMILIES["sewer-line/overview.html"] = family_overview(
    "sewer-line", "Sewer Line Services",
    "Sewer problems, {X}.", "solved for good",
    "Camera inspections, repairs, and cleaning for main sewer lines — real diagnosis before anyone digs.",
    pillset("SEWER LINE SERVICES", SEW_PILLS, "Overview"),
    "SEWER TROUBLE?", "Signs your main line is struggling.",
    ["Multiple drains backing up", "Sewage smells inside or out", "Gurgling toilets",
     "Soggy patches in the yard", "Clogs that keep returning", "Older home with clay pipes"],
    "Sewage backing up indoors? Stop running water and call {tel} — that's a main-line emergency.",
    "Inspect it, clean it, or repair it.",
    [{"title": "Sewer Repair", "desc": "Spot repairs and replacements — trenchless options where possible.", "href": "/plumbing/sewer-line/repair"},
     {"title": "Sewer Cleaning", "desc": "Hydro-jetting that scours the line clean — roots, grease, and all.", "href": "/plumbing/sewer-line/cleaning"},
     {"title": "Camera Inspection", "desc": "See exactly what's wrong before spending a dollar on digging.", "href": "/plumbing/sewer-line/repair"}],
    ("Fixed with proof", "Camera-verified before and after — you see exactly what you paid for."),
    [SPEED_FAQ,
     {"q": "Do you have to dig up my yard?",
      "a": "Not always — camera inspection tells us first, and trenchless repair handles many failures without excavation."},
     {"q": "Why do my drains keep backing up?",
      "a": "Recurring whole-house backups usually mean roots, bellies, or breaks in the main line — a camera finds which."}],
    [{"title": "Clogged Drain", "href": "/plumbing/clogged-drain"},
     {"title": "Leak Detection", "href": "/plumbing/leak-detection"},
     {"title": "Sump Pump Services", "href": "/plumbing/sump-pump/overview"}])

PLUMB_FAMILIES["sump-pump/overview.html"] = family_overview(
    "sump-pump", "Sump Pump Services",
    "Dry basements, {X}.", "guaranteed",
    "Sump pump repair, replacement, and battery backups — protection that works the night the storm hits.",
    pillset("SUMP PUMP SERVICES", SUMP_PILLS, "Overview"),
    "PUMP WORRIES?", "Signs your basement is at risk.",
    ["Pump runs constantly or never", "Grinding or rattling noises", "Pit fills faster than it empties",
     "Pump is 7+ years old", "No battery backup", "Musty basement smells"],
    "Storm season doesn't wait — call {tel} before the next heavy rain tests your pump.",
    "Repair, replace, and back up.",
    [{"title": "Sump Pump Repair", "desc": "Switches, floats, and check valves — fixed before the next storm.", "href": "/plumbing/sump-pump/repair"},
     {"title": "Sump Pump Installation", "desc": "Right-sized pumps installed clean — with high-water alarms.", "href": "/plumbing/sump-pump/installation"},
     {"title": "Battery Backups", "desc": "Power fails in the same storms that flood — backups keep pumping.", "href": "/plumbing/sump-pump/installation"}],
    ("Tested under load", "We flood-test the pit and verify the full cycle before we leave."),
    [SPEED_FAQ,
     {"q": "How long do sump pumps last?",
      "a": "About 7–10 years. Past that, replacement before failure beats a flooded basement after."},
     {"q": "Do I really need a battery backup?",
      "a": "If your basement is finished or storms knock out your power — yes. It's the cheapest flood insurance you can buy."}],
    [{"title": "Leak Detection", "href": "/plumbing/leak-detection"},
     {"title": "Sewer Line Services", "href": "/plumbing/sewer-line/overview"},
     {"title": "Emergency Plumbing", "href": "/plumbing/emergency-plumbing"}])

PLUMB_FAMILIES["gas-line/overview.html"] = family_overview(
    "gas-line", "Gas Line Services",
    "Gas work, {X}.", "done safely",
    "Gas line installation, repair, and appliance hookups — licensed, pressure-tested, and code-compliant every time.",
    pillset("GAS LINE SERVICES", GAS_PILLS, "Overview"),
    "GAS CONCERNS?", "When to call a licensed pro.",
    ["Rotten-egg smell anywhere", "Hissing near gas appliances", "Dead grass over the gas line",
     "New appliance needs a hookup", "Old or corroded piping", "Pilot lights that won't stay lit"],
    "<b>Safety first:</b> smell gas? Leave the house first — don't flip switches — then call {tel} and your utility.",
    "Install, repair, and connect.",
    [{"title": "Gas Line Repair", "desc": "Leaks located, repaired, and pressure-tested — safety-first, always.", "href": "/plumbing/gas-line/repair"},
     {"title": "Gas Line Installation", "desc": "New runs for ranges, dryers, grills, and generators — to code.", "href": "/plumbing/gas-line/installation"},
     {"title": "Appliance Hookups", "desc": "Safe connections with proper shutoffs and leak checks.", "href": "/plumbing/gas-line/installation"}],
    ("Tested and certified", "Every job ends with a pressure test and leak check — documented."),
    [{"q": "How fast can you respond to a gas concern?",
      "a": "Suspected leaks get priority dispatch — and if you smell gas now, leave first and call from outside."},
     {"q": "Can you add a gas line for my grill or range?",
      "a": "Yes — sized, run, and tested to code, with a proper shutoff at the appliance."},
     {"q": "Who handles permits?",
      "a": "We do — permits and inspection scheduling are part of the job."}],
    [{"title": "Emergency Plumbing", "href": "/plumbing/emergency-plumbing"},
     {"title": "Water Heater Services", "href": "/plumbing/water-heater/overview"},
     {"title": "Leak Detection", "href": "/plumbing/leak-detection"}],
    safety=True)

def plumb_sub(folder, child, name_parent, parent_href, pills, active, h1, hl, intro,
              sym_eyebrow, sym_h2, symptoms, callout, process_, decision, faqs,
              book_eyebrow, book_title, book_sub, sibs, safety=False, schedule_label="Schedule Service"):
    return sub(
        [PLUMB_CRUMB, (name_parent, parent_href), (active, "")],
        h1, hl, intro, pillset(pills[0], pills[1], active),
        sym_eyebrow, sym_h2, symptoms, callout, process_, decision,
        f"{active.upper()} QUESTIONS", faqs, book_eyebrow, book_title, book_sub,
        pills[0], sibs, safety=safety, schedule_label=schedule_label, promo="scheduleFast")

PLUMB_FAMILIES["water-heater/repair.html"] = plumb_sub(
    "water-heater", "repair", "Water Heater Services", "/plumbing/water-heater/overview",
    ("WATER HEATER SERVICES", WH_PILLS), "Repair",
    "Water heater repair, {X}.", "priced upfront",
    "Elements, thermostats, valves, and pilot problems — diagnosed fast and fixed the same day in most cases.",
    "NO HOT WATER?", "Common failures we fix daily.",
    ["No hot water at all", "Runs out faster than it used to", "Pilot light won't stay lit",
     "Popping or rumbling sounds", "Lukewarm at every tap", "Breaker trips on electric units"],
    "No hot water this morning? Call {tel} — repairs get priority dispatch.",
    steps("Hot water, same day", "Most repairs finish in one visit — tested at the tap before we go.",
          step1={"title": "Book in minutes", "desc": "No-hot-water calls get priority dispatch."}),
    {"title": "Repair or replace?",
     "desc": "If the tank itself leaks or the unit is 10+ years old, replacement usually wins. We'll price both honestly.",
     "linkLabel": "Water Heater Installation →", "href": "/plumbing/water-heater/installation"},
    [{"q": "How fast can you fix my water heater?",
      "a": "Same day in most cases — no-hot-water calls get priority, and we stock common parts on the truck."},
     {"q": "Is it worth repairing an older unit?",
      "a": "Past 10 years, usually not — a failing tank often leaks next. We'll give you repair and replace numbers side by side."},
     {"q": "Gas and electric — do you fix both?",
      "a": "Yes — tank and tankless, gas and electric, every major brand."}],
    "BOOK WATER HEATER REPAIR", "No hot water? We're on it.", "Priority dispatch for no-hot-water calls.",
    [{"title": "Water Heater Overview", "href": "/plumbing/water-heater/overview"},
     {"title": "Water Heater Installation", "href": "/plumbing/water-heater/installation"},
     {"title": "Leak Detection", "href": "/plumbing/leak-detection"}],
    schedule_label="Schedule Repair")

PLUMB_FAMILIES["water-heater/installation.html"] = plumb_sub(
    "water-heater", "installation", "Water Heater Services", "/plumbing/water-heater/overview",
    ("WATER HEATER SERVICES", WH_PILLS), "Installation",
    "A new water heater, {X}.", "often same-day",
    "Right-sized tank and tankless installations — to code, tested at every tap, old unit hauled away.",
    "TIME TO REPLACE?", "Signs a new unit makes sense.",
    ["Tank is 10+ years old", "Rusty water from hot taps", "Water pooling at the base",
     "Repairs getting frequent", "Never enough hot water", "Thinking about tankless"],
    "Replacing before failure beats a flooded utility room — call {tel} for honest numbers.",
    steps("Installed and hauled away", "Set to code, tested at every tap, and the old unit gone when we leave.",
          step2={"title": "Sized & quoted upfront", "desc": "Sized to your household's real hot-water use — flat pricing with financing options."}),
    {"title": "Tank or tankless?",
     "desc": "Tanks cost less upfront; tankless delivers endless hot water and lower bills. We'll lay out both for your home honestly.",
     "linkLabel": "Water Heater Overview →", "href": "/plumbing/water-heater/overview"},
    [{"q": "Can you install a water heater the same day?",
      "a": "Usually — we stock common tank sizes, so most replacements happen the day you approve the quote."},
     {"q": "What size should I get?",
      "a": "A family of four typically needs 40–50 gallons; we size to your actual usage, not a guess."},
     {"q": "Is financing available?",
      "a": "Yes — flexible monthly options on qualifying installations."}],
    "BOOK AN INSTALLATION", "Same-day replacement, most cases.", "Free estimates with honest sizing.",
    [{"title": "Water Heater Overview", "href": "/plumbing/water-heater/overview"},
     {"title": "Water Heater Repair", "href": "/plumbing/water-heater/repair"},
     {"title": "Water Treatment", "href": "/plumbing/water-treatment"}],
    schedule_label="Schedule Estimate")

PLUMB_FAMILIES["sewer-line/repair.html"] = plumb_sub(
    "sewer-line", "repair", "Sewer Line Services", "/plumbing/sewer-line/overview",
    ("SEWER LINE SERVICES", SEW_PILLS), "Repair",
    "Sewer repair, {X}.", "with proof",
    "Camera-diagnosed sewer repairs — trenchless where possible, dug only where necessary, verified after.",
    "BROKEN LINE?", "Signs your sewer needs repair, not just cleaning.",
    ["Backups return after cleaning", "Soggy or sunken yard patches", "Sewage smells outside",
     "Foundation cracks near the line", "Camera shows breaks or bellies", "Clay pipe with root intrusion"],
    "Repeat backups mean the line itself is failing — call {tel} for a camera look before it collapses.",
    steps("Repaired and re-scoped", "We camera the line after repair so you see exactly what you paid for.",
          step2={"title": "Camera first, quote second", "desc": "No guesswork — you see the break before we price the fix."}),
    {"title": "Repair or clean?",
     "desc": "If the pipe is intact but clogged, hydro-jetting may be all you need — at a fraction of repair cost.",
     "linkLabel": "Sewer Cleaning →", "href": "/plumbing/sewer-line/cleaning"},
    [{"q": "How fast can you repair a sewer line?",
      "a": "Camera diagnosis usually same or next day; most repairs complete within days, not weeks."},
     {"q": "Is trenchless repair really possible?",
      "a": "Often, yes — pipe bursting and lining fix many failures without excavating the yard."},
     {"q": "Will insurance cover it?",
      "a": "Sometimes — we document everything with camera footage to support your claim."}],
    "BOOK SEWER REPAIR", "Backups keep returning?", "Camera-first diagnosis, honest pricing.",
    [{"title": "Sewer Line Overview", "href": "/plumbing/sewer-line/overview"},
     {"title": "Sewer Cleaning", "href": "/plumbing/sewer-line/cleaning"},
     {"title": "Clogged Drain", "href": "/plumbing/clogged-drain"}],
    schedule_label="Schedule Repair")

PLUMB_FAMILIES["sewer-line/cleaning.html"] = plumb_sub(
    "sewer-line", "cleaning", "Sewer Line Services", "/plumbing/sewer-line/overview",
    ("SEWER LINE SERVICES", SEW_PILLS), "Cleaning",
    "Sewer cleaning that {X}.", "actually lasts",
    "Hydro-jetting scours the full pipe wall clean — roots, grease, and scale — not just a hole through the clog.",
    "SLOW EVERYTHING?", "Signs your main line needs cleaning.",
    ["Whole-house drains run slow", "Gurgling after flushing", "Grease-heavy kitchen line",
     "Roots found on camera", "Annual backups like clockwork", "Never been jetted"],
    "Snaking pokes a hole; jetting cleans the pipe — call {tel} to break the backup cycle.",
    steps("Scoured and scoped", "Post-cleaning camera pass confirms a clean pipe wall, end to end.",
          step2={"title": "Jet, don't just poke", "desc": "High-pressure water scours the full diameter — roots, grease, and scale."}),
    {"title": "Cleaning or repair?",
     "desc": "If the camera shows breaks or bellies, cleaning alone won't hold — we'll show you the footage and price both.",
     "linkLabel": "Sewer Repair →", "href": "/plumbing/sewer-line/repair"},
    [{"q": "How fast can you jet my line?",
      "a": "Usually same or next day — and backups get priority."},
     {"q": "How long does hydro-jetting last?",
      "a": "Years for most homes — grease-heavy or root-prone lines benefit from scheduled maintenance jetting."},
     {"q": "Is jetting safe for old pipes?",
      "a": "We camera first — if the pipe is too fragile, we'll tell you before jetting, not after."}],
    "BOOK SEWER CLEANING", "Break the backup cycle.", "Camera-verified clean, upfront price.",
    [{"title": "Sewer Line Overview", "href": "/plumbing/sewer-line/overview"},
     {"title": "Sewer Repair", "href": "/plumbing/sewer-line/repair"},
     {"title": "Clogged Drain", "href": "/plumbing/clogged-drain"}])

PLUMB_FAMILIES["sump-pump/repair.html"] = plumb_sub(
    "sump-pump", "repair", "Sump Pump Services", "/plumbing/sump-pump/overview",
    ("SUMP PUMP SERVICES", SUMP_PILLS), "Repair",
    "Sump pump repair, {X}.", "before the storm",
    "Floats, switches, check valves, and clogs — repaired and flood-tested before the next heavy rain.",
    "PUMP PROBLEMS?", "Failures we fix before they flood.",
    ["Pump won't turn on", "Runs but doesn't move water", "Cycles constantly",
     "Stuck or jammed float", "Rattling or grinding", "Pit overflows in storms"],
    "A pump that's acting up will fail on the worst night — call {tel} before the forecast turns.",
    steps("Flood-tested before we go", "We fill the pit and verify full cycles — not just a hum.",
          step1={"title": "Book in minutes", "desc": "Storm-season calls get priority — don't wait for the radar."}),
    {"title": "Repair or replace?",
     "desc": "Pumps past 7 years or with motor failures are usually smarter to replace — often with a backup added.",
     "linkLabel": "Sump Pump Installation →", "href": "/plumbing/sump-pump/installation"},
    [{"q": "How fast can you repair my sump pump?",
      "a": "Same day in most cases — and priority when storms are in the forecast."},
     {"q": "Why does my pump run constantly?",
      "a": "Usually a stuck float, failed check valve, or an undersized pump — all fixable, all testable in one visit."},
     {"q": "Should I test my own pump?",
      "a": "Yes — pour a bucket of water in the pit each spring. If it doesn't cycle cleanly, call us."}],
    "BOOK PUMP REPAIR", "Storm coming? We're on it.", "Priority dispatch in storm season.",
    [{"title": "Sump Pump Overview", "href": "/plumbing/sump-pump/overview"},
     {"title": "Sump Pump Installation", "href": "/plumbing/sump-pump/installation"},
     {"title": "Emergency Plumbing", "href": "/plumbing/emergency-plumbing"}],
    schedule_label="Schedule Repair")

PLUMB_FAMILIES["sump-pump/installation.html"] = plumb_sub(
    "sump-pump", "installation", "Sump Pump Services", "/plumbing/sump-pump/overview",
    ("SUMP PUMP SERVICES", SUMP_PILLS), "Installation",
    "Sump pumps installed {X}.", "storm-ready",
    "Right-sized primary pumps and battery backups — installed clean, alarmed, and tested under load.",
    "TIME TO UPGRADE?", "When installation beats another repair.",
    ["Pump is 7+ years old", "Basement is finished", "Power fails in storms",
     "Pit too small or shallow", "No high-water alarm", "History of close calls"],
    "The best time to upgrade is before the water table rises — call {tel} for honest sizing.",
    steps("Tested under load", "We flood-test the full system — primary, backup, and alarm — before we leave.",
          step2={"title": "Sized & quoted upfront", "desc": "Pump capacity matched to your pit, discharge, and water table."}),
    {"title": "Add a battery backup?",
     "desc": "Storms that flood basements also knock out power — a backup keeps pumping when the grid doesn't.",
     "linkLabel": "Sump Pump Overview →", "href": "/plumbing/sump-pump/overview"},
    [{"q": "How fast can you install a sump pump?",
      "a": "Most installations happen within a day or two — same-week even in storm season."},
     {"q": "What size pump do I need?",
      "a": "Depends on your pit, discharge height, and water table — we size it to real conditions, not a shelf label."},
     {"q": "How long do battery backups run?",
      "a": "Quality backups pump intermittently for 24+ hours — enough to outlast most outages."}],
    "BOOK AN INSTALLATION", "Storm-ready, guaranteed.", "Free estimates with honest sizing.",
    [{"title": "Sump Pump Overview", "href": "/plumbing/sump-pump/overview"},
     {"title": "Sump Pump Repair", "href": "/plumbing/sump-pump/repair"},
     {"title": "Leak Detection", "href": "/plumbing/leak-detection"}],
    schedule_label="Schedule Estimate")

PLUMB_FAMILIES["gas-line/repair.html"] = plumb_sub(
    "gas-line", "repair", "Gas Line Services", "/plumbing/gas-line/overview",
    ("GAS LINE SERVICES", GAS_PILLS), "Repair",
    "Gas leaks fixed {X}.", "safely, fast",
    "Suspected leaks located, repaired, and pressure-tested by licensed pros — safety-first at every step.",
    "SMELL GAS?", "Take these signs seriously.",
    ["Rotten-egg smell indoors or out", "Hissing near lines or appliances", "Dead grass over buried line",
     "Higher gas bills without cause", "Pilot lights failing repeatedly", "Headaches or dizziness at home"],
    "<b>Safety first:</b> smell gas now? Leave the house — don't flip switches — then call {tel} and your utility from outside.",
    steps("Repaired, tested, documented", "Every repair ends with a pressure test and leak check — documented for your records.",
          step1={"title": "Call from safety", "desc": "Suspected leaks get priority dispatch — we coordinate with your utility."}),
    {"title": "Aging gas lines?",
     "desc": "Corroded or undersized lines fail again — sometimes a new run is the safer, cheaper answer.",
     "linkLabel": "Gas Line Installation →", "href": "/plumbing/gas-line/installation"},
    [{"q": "How fast do you respond to gas leaks?",
      "a": "Priority dispatch, around the clock — but leave the house first and call from outside."},
     {"q": "How do you find a gas leak?",
      "a": "Electronic detection and pressure testing locate leaks precisely — including buried lines."},
     {"q": "Can I keep using other appliances?",
      "a": "Not until the system is tested safe — we'll tell you exactly what's usable and when."}],
    "SUSPECTED LEAK?", "Leave first. Then call.", "Priority dispatch for gas concerns.",
    [{"title": "Gas Line Overview", "href": "/plumbing/gas-line/overview"},
     {"title": "Gas Line Installation", "href": "/plumbing/gas-line/installation"},
     {"title": "Emergency Plumbing", "href": "/plumbing/emergency-plumbing"}],
    safety=True, schedule_label="Schedule Repair")

PLUMB_FAMILIES["gas-line/installation.html"] = plumb_sub(
    "gas-line", "installation", "Gas Line Services", "/plumbing/gas-line/overview",
    ("GAS LINE SERVICES", GAS_PILLS), "Installation",
    "New gas lines, {X}.", "run to code",
    "Ranges, dryers, grills, fire pits, and generators — new gas runs sized, installed, and tested to code.",
    "ADDING GAS?", "What we run lines for.",
    ["Gas range or cooktop", "Clothes dryer conversion", "Outdoor grill or fire pit",
     "Standby generator", "Garage heater", "Pool or spa heater"],
    "Planning a project? Call {tel} early — a right-sized line saves headaches later.",
    steps("Connected and certified", "Pressure-tested, leak-checked, and inspected — with permits handled.",
          step2={"title": "Sized & quoted upfront", "desc": "BTU load calculated across appliances so everything runs right."}),
    {"title": "Upgrading appliances too?",
     "desc": "If old lines are corroded or undersized, we'll flag it during the estimate — before it's a problem.",
     "linkLabel": "Gas Line Repair →", "href": "/plumbing/gas-line/repair"},
    [{"q": "How fast can you run a new gas line?",
      "a": "Most residential runs are done in a day once permits clear — we handle the paperwork."},
     {"q": "Do I need a permit?",
      "a": "Yes for most gas work — and we pull it, schedule inspection, and close it out for you."},
     {"q": "Can you convert my dryer or range to gas?",
      "a": "Yes — line, shutoff, and safe hookup, tested before first use."}],
    "BOOK AN ESTIMATE", "Project-ready gas runs.", "Permits and inspection handled.",
    [{"title": "Gas Line Overview", "href": "/plumbing/gas-line/overview"},
     {"title": "Gas Line Repair", "href": "/plumbing/gas-line/repair"},
     {"title": "Water Heater Services", "href": "/plumbing/water-heater/overview"}],
    schedule_label="Schedule Estimate")
